spring.application.name=musicplayer

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d70nj2k9c44c73b45vcg-a:5432/musicdb_qzjt
spring.datasource.username=musicdb_qzjt_user
spring.datasource.password=XX2763BNMMvP8inP4mVFavVdGz7eONs3
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

server.port=${PORT:8080}