spring.application.name=musicplayer

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# ✅ PostgreSQL (Render DB)
spring.datasource.url=jdbc:postgresql://dpg-d70fk3hr0fns73cqnd20-a:5432/music_db_p3my
spring.datasource.username=music_db_p3my_user
spring.datasource.password=UnawcFlICQiYAtnNZS0GQmofMIBrcBuM
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

server.port=${PORT:8080}